development:
  adapter: postgresql
  database: pykih_publishing_dev2
  username: developer
  password: developer
  host: localhost
  port: 5432
  pool: 25

production:
  adapter: postgresql
  database: <%= ENV['PRODUCTION_DB_NAME'] %>
  username: <%= ENV['PRODUCTION_DB_USER'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
  port: 5432
  pool: 25